num1 = input("Enter Num1:")
num2 = input("Enter Num2:")
float(num1)
int(num2)
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** num2)