namec = str(input("Enter cars name:"))
colorc = str(input("Enter cars color:"))
prisec = float(input("Enter cars prise"))
reelesc = int(input("Enter cars reeles date:"))
print("cars name is"+""+namec+""+"car color is"+""+colorc+""+"date of reeles is"+""+reelesc+""+"which cost"+""+prisec)